name: certificate_transparency
description: Certificate transparency implementation for dart
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: ^1.0.0
  crypto: ^3.0.1
  crypto_keys: ^0.3.0
  http: ^0.13.1
  json_annotation: ^4.0.1
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  pedantic: ^1.11.0
  test: ^1.16.8
